/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_DOABLE_ITEMS_ITEMS_PB_H_INCLUDED
#define PB_DOABLE_ITEMS_ITEMS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _doable_items_Shirt_Size {
    doable_items_Shirt_Size_SMALL = 0,
    doable_items_Shirt_Size_MEDIUM = 1,
    doable_items_Shirt_Size_LARGE = 2
} doable_items_Shirt_Size;

/* Struct definitions */
/* A snazzy new shirt! */
typedef struct _doable_items_Shirt {
    pb_callback_t color;
    doable_items_Shirt_Size size;
} doable_items_Shirt;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _doable_items_Shirt_Size_MIN doable_items_Shirt_Size_SMALL
#define _doable_items_Shirt_Size_MAX doable_items_Shirt_Size_LARGE
#define _doable_items_Shirt_Size_ARRAYSIZE ((doable_items_Shirt_Size)(doable_items_Shirt_Size_LARGE+1))

#define doable_items_Shirt_size_ENUMTYPE doable_items_Shirt_Size


/* Initializer values for message structs */
#define doable_items_Shirt_init_default          {{{NULL}, NULL}, _doable_items_Shirt_Size_MIN}
#define doable_items_Shirt_init_zero             {{{NULL}, NULL}, _doable_items_Shirt_Size_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define doable_items_Shirt_color_tag             1
#define doable_items_Shirt_size_tag              2

/* Struct field encoding specification for nanopb */
#define doable_items_Shirt_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   color,             1) \
X(a, STATIC,   SINGULAR, UENUM,    size,              2)
#define doable_items_Shirt_CALLBACK pb_default_field_callback
#define doable_items_Shirt_DEFAULT NULL

extern const pb_msgdesc_t doable_items_Shirt_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define doable_items_Shirt_fields &doable_items_Shirt_msg

/* Maximum encoded size of messages (where known) */
/* doable_items_Shirt_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
